sudo: required
dist: precise
language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - libffi-dev
            - libssl-dev

before_install:
    - sudo pip install pyopenssl ndg-httpsclient pyasn1
    - sudo pip install --user cpp-coveralls

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

before_script:
    - mkdir build
    - cd build
    - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..

script:
    - make
    - make coveralls
    - cd tests
    - ./all_tests

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

notifications:
  recipients:
    - agelosbb@gmail.com
  email:
    on_success: always
    on_failure: always