sudo: required
dist: precise
language: cpp
compiler:
    - gcc

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - libffi-dev
            - libssl-dev

before_install:
   - sudo apt-get update
   - sudo pip install requests[security]
   - sudo pip install codecov

install:
    - sudo apt-get install lcov
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

before_script:
    - gcov -version
    - lcov -v
    - gcc -v
    - g++ -v
    - mkdir build
    - cd build
    - cmake -DCOVERAGE=ON ..

script:
    - make -j4
    - ./tests/all_tests
    - find . -iname "*.gcda" -type f -exec mv {} . \;
    - find . -iname "*.o" -type f -exec mv {} . \;
    - find . -iname "*.gcno" -type f -exec mv {} . \;
    - find . -iname "*.gcno" -type f -exec gcov {} \;

after_success:
    - codecov -X gcov

notifications:
  recipients:
    - agelosbb@gmail.com
  email:
    on_success: always
    on_failure: always