sudo: required
dist: trusty
language: cpp
compiler:
    - gcc-5

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5

before_install:
   - sudo apt-get update
   - sudo pip install requests[security]
   - sudo pip install codecov

install:
    - sudo apt-get install gcc-5 g++-5
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 20
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++
    - sudo find /usr/bin/ -name "gcov*"

before_script:
    - gcov -version
    - gcc -v
    - g++ -v
    - mkdir build
    - cd build
    - cmake -DCOVERAGE=ON ..

script:
    - make -j4
    - ./tests/all_tests
    - find . -iname "*.gcda" -type f -exec mv {} . \;
    - find . -iname "*.o" -type f -exec mv {} . \;
    - find . -iname "*.gcno" -type f -exec mv {} . \;
    - find . -iname "*.gcno" -type f -exec gcov {} \;

after_success:
    - sudo codecov -X ./usr/bin/gcov-5

notifications:
  recipients:
    - agelosbb@gmail.com
  email:
    on_success: always
    on_failure: always