sudo: required
dist: precise
language: cpp
compiler:
    - gcc

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - libffi-dev
            - libssl-dev

before_install:
   - sudo apt-get install lcov rubygems
   - sudo gem install lcoveralls

install:
    - sudo pip install requests[security]
    - sudo apt-get install lcov
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

before_script:
    - gcov -version
    - gcc -version
    - g++ -version
    - mkdir build
    - cd build
    - cmake -DCOVERAGE=ON ..

script:
    - make
    - cd tests
    - ./all_tests
    - cd CMakeFiles/all_tests.dir/
    - find . -type f -iname "*.gc*" -exec mv {} . \;
    - lcov -c -d . -o all_tests.info

after_success:
  - lcoveralls --root .. -v

notifications:
  recipients:
    - agelosbb@gmail.com
  email:
    on_success: always
    on_failure: always